### ISSUE TITLE
Re-education Module (CLOSE THE DOOR!!)

### ISSUE THREAD

**Issue by sedmonds** [sudoroom/sudobot#2]
Request from #sudoroom:

Patron forgets to look door after 'swipe' and 'enter'. Create module to:
1) 5 minute listener for door close and if no lock,
2) Flags user and adds to log.

3) Re-education (log file)

Any help in making this is VERY, VERY helpful and educational.

**Comment by jerkey** [comment]
we miss you!  the door doesn't have a "lock" function anymore because it locks when it closes, and there is a spring-loaded automatic closer.  and we don't have a sensor to detect whether the door is open or not, at this point.

soon we'll add a door to the actual sudoroom, maybe it will have more sensors.
